// eslint-disable-next-line no-unused-vars
import Navigation from '../components/Navigation'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en" className='bg-black text-white'>
      <head>
        <title>
          Mi first app with nextjs 13
        </title>
      </head>
      <body>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
